subtitle/urls.py
from django.urls import path

from subtitle import views

urlpatterns = [
    path("movie/<int:db_id>", views.MovieDetailWithSubtitleList.as_view(), name="movie_detail"),
    path("tv/<int:db_id>", views.TvDetailList.as_view(), name="tv_detail"),
    path("tv/<int:db_id>/season/<int:season_number>/", views.TvSeasonList.as_view(), name="tv_seasons"),
    path("tv/<int:db_id>/season/<int:season_number>/episode/<int:episode_number>", views.TvEpisodeList.as_view(),
         name="tv_episodes"),
    # path("collection/<int:id>", views.CollectionDetail.as_view(), name="collection_detail"),
    path("movie_upload", views.CreateMovieSubView.as_view(), name="movie-sub-upload"),
    path("tv_upload", views.CreateTvSubView.as_view(), name="tv-sub-upload"),
]

subworld/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('movie/', views.MovieIndexView.as_view(), name='movie_index'),
    path('tv_show/', views.TvShowIndexView.as_view(), name='tv_show_index'),
    path('d/', include('subtitle.urls')),
    path('s/', include('search.urls')),
    # path("checkdb", views.DbInit.as_view(), name='db_init'),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('moviedb/', include('moviedb.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("test", views.Test.as_view(), name = "test"),
    path('signup/', views.SignUp.as_view(), name = "signup"),
]

search/models.py
from django.db import models


# Create your models here.

class MovieDB(models.Model):
    adult = models.BooleanField(default=False)
    title = models.CharField(max_length=255, null=True)
    original_title = models.CharField(max_length=255)
    poster_path = models.CharField(max_length=255, default="", null=True)
    backdrop_path = models.CharField(max_length=255, default="", null=True)
    popularity = models.FloatField()
    video = models.BooleanField(default=False)

    def __str__(self):
        return self.original_title


class GenreDB(models.Model):
    name = models.CharField(max_length=126)

    def __str__(self):
        return self.name


class CollectionDB(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class KeywordDB(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class PersonDB(models.Model):
    adult = models.BooleanField(default=False)
    name = models.CharField(max_length=255)
    poster_path = models.CharField(max_length=255, default="", null=True)
    backdrop_path = models.CharField(max_length=255, default="", null=True)
    popularity = models.FloatField()

    def __str__(self):
        return self.name


class ProductionCompanyDB(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class TvNetworkDB(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class TvSeriesDB(models.Model):
    original_name = models.CharField(max_length=255)
    name = models.CharField(max_length=255, null=True)
    poster_path = models.CharField(max_length=255, default="", null=True)
    backdrop_path = models.CharField(max_length=255, default="", null=True)
    popularity = models.FloatField()

    def __str__(self):
        return self.original_name

subtitle/models.py
from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

from moviedb.models import Movie, TvSeries, TvSeason, TvEpisode, Language


# Create your models here.

class MovieSubtitleInfo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=1024)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    rate_good = models.IntegerField(default=0)
    rate_bad = models.IntegerField(default=0)
    upload_date = models.DateTimeField(auto_now_add=True)
    downloaded = models.IntegerField(default=0)
    comment = RichTextField(blank=True, null=True)


class TvSubtitleInfo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tv_series = models.ForeignKey(TvSeries, on_delete=models.CASCADE)
    tv_season = models.ForeignKey(TvSeason, on_delete=models.CASCADE)
    tv_episode = models.ForeignKey(TvEpisode, on_delete=models.CASCADE)
    title = models.CharField(max_length=1024)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    rate_good = models.IntegerField(default=0)
    rate_bad = models.IntegerField(default=0)
    upload_date = models.DateTimeField(auto_now_add=True)
    downloaded = models.IntegerField(default=0)
    comment = RichTextField(blank=True, null=True)


class MovieSubtitles(models.Model):
    file = models.FileField()
    info = models.ForeignKey(MovieSubtitleInfo, on_delete=models.CASCADE)


class TvSubtitles(models.Model):
    file = models.FileField()
    info = models.ForeignKey(TvSubtitleInfo, on_delete=models.CASCADE)

subtitle/forms.py
import os

from django import forms
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _

from .models import MovieSubtitleInfo, TvSubtitleInfo

CONTENT_TYPES = ['image', 'video', 'smi']
FILE_EXTENSIONS = ['.psb', '.srt', '.ssa', '.ass', '.sub', '.sami', '.smil', '.smi', '.usf', '.vtt']
# 2.5MB - 2621440
# 5MB - 5242880
# 10MB - 10485760
# 20MB - 20971520
# 50MB - 5242880
# 100MB - 104857600
# 250MB - 214958080
# 500MB - 429916160
MAX_UPLOAD_SIZE = "2621440"


class TvShowSubtitleForm(forms.ModelForm):
    class Meta:
        model = TvSubtitleInfo
        fields = ("title", "tv_series", "tv_season", "tv_episode", "language", "comment")
        widgets = {
            'movie': forms.HiddenInput(),
            'season_id': forms.Select(),
            'episode_id': forms.Select(),
        }

    def clean_sub_file(self):
        sub_file = self.cleaned_data['sub_file']
        file_type = os.path.splitext(sub_file.name)[1]

        if file_type in FILE_EXTENSIONS:
            if sub_file.size > int(MAX_UPLOAD_SIZE):
                raise forms.ValidationError(
                    _(u"Max Size: %s Your file size is too big.") % (filesizeformat(sub_file.size))
                )
        else:
            raise forms.ValidationError(
                _(u"Extension Error: %s is not valid file format") % (file_type)
            )
        return sub_file


class MovieSubtitleForm(forms.ModelForm):
    class Meta:
        model = MovieSubtitleInfo
        fields = ("movie", "title", 'language', 'comment')
        widgets = {
            'movie': forms.HiddenInput(),
        }

    def clean_sub_file(self):
        subfile = self.cleaned_data['sub_file']
        file_type = os.path.splitext(subfile.name)[1]

        if file_type in FILE_EXTENSIONS:
            if subfile.size > int(MAX_UPLOAD_SIZE):
                raise forms.ValidationError(
                    _(u"Max Size: %s, Your file size is too big.") % (filesizeformat(subfile.size))
                )
        else:
            raise forms.ValidationError(
                _(u"Extension Error: %s is not valid file format") % (file_type)
            )
        return subfile

subtitle/views.py
# Create your views here.
import os

import tmdbsimple
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy
from django.views import generic

from moviedb.models import Movie, TvSeries, Credit, Videos, Keyword
from subtitle.models import MovieSubtitleInfo, TvSubtitleInfo
from subworld.views import BaseSetMixin, create_update_db
from .forms import MovieSubtitleForm, TvShowSubtitleForm


class MovieDetailWithSubtitleList(BaseSetMixin, generic.ListView):
    model = MovieSubtitleInfo
    ordering = ('title', 'language',)
    locator = "movie_detail"
    template_name = 'subtitle/movie_detail.html'

    def get_queryset(self):
        print("kwargs: ", self.kwargs)
        queryset = MovieSubtitleInfo.objects.filter(movie_id=self.kwargs['db_id'])[:20]

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(MovieDetailWithSubtitleList, self).get_context_data(*args, **kwargs)
        movie_id = self.kwargs['db_id']
        movie = Movie.initialize.get_or_create_movie(movie_id=movie_id)
        credit = Credit.movie_initialize.update_or_create_credit(movie_id=movie_id)
        video = Videos.movie_initialize.get_or_create_video(movie_id=movie_id)
        keyword = Movie.initialize.get_or_create_movie(movie_id).keyword

        context['movie'] = movie
        context['credits'] = credit
        context['videos'] = video
        context['keywords'] = keyword
        return context


class TvDetailList(BaseSetMixin, generic.ListView):
    model = TvSubtitleInfo
    template_name = 'subtitle/tv_show_subtitle_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TvDetailList, self).get_context_data(*args, **kwargs)
        tv_show = self.tmdb.TV(id=self.kwargs['db_id'])
        create_update_db(TvSeries, tv_show.info())
        context['tv_show'] = tv_show.info()
        context['images'] = tv_show.images()
        context['videos'] = tv_show.videos()
        context['persons'] = tv_show.credits()

        return context


class TvSeasonList(BaseSetMixin, generic.ListView):
    model = TvSubtitleInfo
    template_name = 'subtitle/tv_season_subtitle_list.html'


class TvEpisodeList(BaseSetMixin, generic.ListView):
    model = TvSubtitleInfo
    template_name = 'subtitle/tv_episode_subtitle_list.html'


class CreateMovieSubView(BaseSetMixin, generic.CreateView):
    model = MovieSubtitleInfo
    form_class = MovieSubtitleForm
    locator = 'upload_movie'

    def get_success_url(self, **kwargs):

        return reverse_lazy("movie_detail", args=(self.object.db_id.pk,))

    def form_invalid(self, form):
        print(form.errors)

        return super(CreateMovieSubView, self).form_invalid(form)

    def form_valid(self, form):
        print(form.cleaned_data)
        subtitle = form.save(commit=False)
        subtitle.user = self.request.user
        if self.request.FILES:
            upload_file = self.request.FILES['sub_file']
            subtitles = MovieSubtitleInfo.objects.all()
            if upload_file.name in subtitles:
                print("file is already exist.")

            path_1 = ""
            fs = FileSystemStorage()

            db_id = subtitle.db_id
            language = subtitle.language

            file_path = os.path.join(path_1, str(db_id), language.iso_639_1, upload_file.name)
            print(file_path)
            fs.save(file_path, upload_file)

            form.user = self.request.user
            form.save()
            return super(CreateMovieSubView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateMovieSubView, self).get_context_data(**kwargs)
        if self.request.GET:
            tmdbsimple.API_KEY = settings.TMDB_API_KEY
            context['info'] = tmdbsimple.Movies(self.request.GET.get('movie_id')).info()
            return context

        return context


class CollectionDetail(generic.TemplateView):
    pass


class CreateTvSubView(BaseSetMixin, generic.CreateView):
    model = TvSubtitleInfo
    form_class = TvShowSubtitleForm
    locator = 'upload_tv_show'

    def get_success_url(self, **kwargs):
        return reverse_lazy("tv_detail", args=(self.object.db_id.pk,))

    def get_context_data(self, **kwargs):
        context = super(CreateTvSubView, self).get_context_data(**kwargs)
        if self.request.GET:
            tmdbsimple.API_KEY = settings.TMDB_API_KEY
            context['info'] = tmdbsimple.TV(self.request.GET.get('tv_id')).info()
            return context

        return context

templates/subtitle/moviesubtitle_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load socialaccount %}

{% block body %}

    <div class="container" id="movie_info">
        <div class="card card-cascade wider mb-4">
            {#            <div class="view view-cascade">#}
            {#                <img id="info_image" src="{{ image_base.base_url }}/{{ backdrop_size.w780 }}{{ info.backdrop_path }}"#}
            {#                     class="card-img-top lazy"/>#}
            {#                <a href="#">#}
            {#                    <div class="mask rgba-white-light"></div>#}
            {#                </a>#}
            {#            </div>#}

            <div class="card-body card-body-cascade text-center">
                <div class="row">
                    <div class="col-md-4 z-depth-1 px-0">
                        <img id="info_poster"
                             src="{{ image_base.base_url }}/{{ poster_size.w342 }}{{ info.poster_path }}"
                             class="card-img"/>
                    </div>
                    <div class="col-md-8">
                        <h4 class="card-title" id="info_title"><strong>{{ info.title }}</strong></h4>
                        <h4 class="indigo-text" id="info_tagline"><strong>{{ info.tagline }}</strong></h4>
                        <p class="card-text" id="info_overview">{{ info.overview }}</p>

                    </div>
                </div>
            </div>
        </div>
        <div class="card m-3 p-2">

            <form class="form-elegant z-depth-1 range-field" method="post" action="{% url 'sub-upload' %}"
                  enctype="multipart/form-data">
                {#<div class="field {{ field|field_type }} {{ field|widget_type }} {{ field.html_name }}">#}
                {% csrf_token %}
                {{ form.media }}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {% if field|field_type == "modelchoicefield" %}
                            {{ field|add_class:'mdb-select md-form'|attr:"searchable=search here" }}
                        {% else %}
                            {{ field|add_class:"form-control" }}
                        {% endif %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">{{ error }}</div>

                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}

                <button class="btn btn-success" type="submit">Upload</button>
            </form>

        </div>

    </div>
{% endblock %}


{% block script %}
    <script>

        $('#id_title').autocomplete({
            source: "{% url 'movie_autocomplete' %}",
            minLength: 2,
            delay: 300,
            select: function (e, info) {
                $("#id_db_id").val(info.item.value);
                e.preventDefault();
                $('#id_title').val(info.item.label);
                $.ajax({
                    type: "GET",
                    delay: 300,
                    url: "{% url 'autoinfo' '123' %}".replace(/123/, info.item.value),
                    success: function (data) {
                        info = $('#movie_info');
                        info.find('#info_title').html(data.title);
                        $(this).val(data.title);
                        var backdrop = "{{ image_base.base_url }}/{{ backdrop_size.w780 }}" + data.backdrop_path;
                        var poster = "{{ image_base.base_url }}/{{ poster_size.w185 }}" + data.poster_path;
                        info.find("#info_poster").attr({"src": poster});
                        info.find("#info_image").attr({"src": backdrop});
                        info.find('#info_tagline').html(data.tagline);
                        info.find('#info_overview').html(data.overview);
                    }
                });
            },
            focus: function (e, info) {
                e.preventDefault();
                $('#id_title').val(info.item.label);

            }
        });


        {#$("#id_title").autocomplete({#}
        {#    source: "{% url 'movie_autocomplete' %}",#}
        {#    minLength: 2,#}
        {#    create: function () {#}
        {#        $(this).data('ui-autocomplete')._renderItem = function (ul, item) {#}
        {#            return $("<li>")#}
        {#                .append(item.id + ":" + item.name)#}
        {#                .appendTo(ul);#}
        {#        }#}
        {#    },#}
        {#    select: function (e, info) {#}
        {#        console.log("select", info.item.name);#}
        {#        $("#id_db_id").val(info.item.id);#}
        {#        console.log("this", $(this));#}
        {#        $(this).val(info.item.name);#}
        {#        $.ajax({#}
        {#            type: "GET",#}
        {#            delay: 300,#}
        {#            url: "{% url 'autoinfo' '123' %}".replace(/123/, info.item.id),#}
        {#            success: function (data) {#}
        {#                info = $('#movie_info');#}
        {#                info.find('#info_title').html(data.title);#}
        {#                $(this).val(data.title);#}
        {#                var backdrop = "{{ image_base.base_url }}/{{ backdrop_size.w780 }}" + data.backdrop_path;#}
        {#                var poster = "{{ image_base.base_url }}/{{ poster_size.w185 }}" + data.poster_path;#}
        {#                info.find("#info_poster").attr({"src": poster});#}
        {#                info.find("#info_image").attr({"src": backdrop});#}
        {#                info.find('#info_tagline').html(data.tagline);#}
        {#                info.find('#info_overview').html(data.overview);#}
        {#            }#}
        {#        });#}
        {#    }#}
        {#  });  #}

        $(document).ready(function () {
            $('.mdb-select').materialSelect();
        });
        $('#id_type').val({{ show_type }});
        $('#id_db_id').val({{ info.id }});
        $('#id_title').val('{{ info.title }}');
    </script>
{% endblock %}

templates/subtitle/tvsubtitle_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load socialaccount %}

{% block body %}

    <div class="container" id="movie_info">
        <div class="card card-cascade wider mb-4">
            <div class="card-body card-body-cascade text-center">
                <div class="row">
                    <div class="col-md-4 z-depth-1 px-0">
                        <img id="info_poster"
                             src="{{ image_base.base_url }}/{{ poster_size.w342 }}{{ info.poster_path }}"
                             class="card-img"/>
                    </div>
                    <div class="col-md-8">
                        <h4 class="card-title" id="info_title"><strong>{{ info.name }}</strong></h4>
                        <h4 class="indigo-text" id="info_tagline"><strong>{{ info.tagline }}</strong></h4>
                        <p class="card-text" id="info_overview">{{ info.overview }}</p>

                    </div>
                </div>
            </div>
        </div>
        <div class="card m-3 p-2">

            <form class="form-elegant z-depth-1 range-field" method="post" action="{% url 'movie-sub-upload' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {% if field|field_type == "modelchoicefield" %}
                            {{ field|add_class:'mdb-select md-form'|attr:"searchable=search here" }}
                        {% elif field|field_type == "integerfield" %}
                            {{ field|add_class:'mdb-select md-form' }}
                        {% else %}
                            {{ field|add_class:"form-control" }}
                        {% endif %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">{{ error }}</div>

                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}

                <button class="btn btn-success" type="submit">Upload</button>
            </form>

        </div>

    </div>
{% endblock %}


{% block script %}
    <script>
        var $name = $("#id_name");
        $name.val("{{ info.name }}");
        var $seasons = {{% for season in info.seasons %}
                '{{ forloop.counter }}': '{{ season.name }}',{% endfor %}
        };
        var $episodes = {
            {% for season in info.seasons %}
                "{{ forloop.counter }}": {{% for i in season.episode_count|rjust:season.episode_count %}
                        "{{ forloop.counter }}": "{{ forloop.counter }}",{% endfor %}
                },{% endfor %}
        };
        $name.autocomplete({
            source: function(request, response){
                $.ajax({
                    url:'{% url 'tv_autocomplete' %}',
                    type:"get",
                    dataType:"json",
                    data:{
                        search:request.term,type:'tv_show'
                    },
                    success:function (data) {
                        response(data);
                    }
                });
            },
            minLength: 2,
            data:{
              "type":"tv_show",
            },
            delay: 300,
            select: function (e, info) {
                $("#id_db_id").val(info.item.value);
                e.preventDefault();
                $('#id_name').val(info.item.label);
                $.ajax({
                    type: "GET",
                    delay: 300,
                    url: "{% url 'auto-info' %}",
                    data:{
                        "type": 'tv_show',
                        "db_id": info.item.value,
                    },
                    success: function (data) {
                        info = $('#movie_info');
                        info.find('#info_title').html(data.name);
                        $(this).val(data.name);
                        var poster = "{{ image_base.base_url }}/{{ poster_size.w185 }}" + data.poster_path;
                        info.find("#info_poster").attr({"src": poster});
                        info.find('#info_tagline').html(data.tagline);
                        info.find('#info_overview').html(data.overview);
                        $seasons = [];
                        $episodes = [];
                        console.log(data.seasons);
                        $.each(data.seasons, function (key, value) {
                            $seasons += {key: value};
                            $.each(new Array(data.seasons.episode_count), function (e_key) {
                                $episodes[key] += {e_key: e_key};
                                console.log('updated episodes', $episodes);
                            })
                        })

                    }
                });
            },
            focus: function (e, info) {
                e.preventDefault();
                $('#id_title').val(info.item.label);
            }
        });
        $(document).ready(function () {
            $('.mdb-select').materialSelect();

            update_selection = function(selection, object){
                console.log("update_selection", object);
                selection.empty();
                $.each(object, function (key, value) {
                    selection.append($("<option></option>").attr("value", key).text(value));
                });
            };
            season_select = $("#id_season_id");
            update_selection(season_select, $seasons);
            season_select.change(function () {
                var $season_id = $(this).val();
                update_selection($("#id_episode_id"), $episodes[$season_id]);
            });

        });
    </script>
{% endblock %}